export interface Brand {
  id: number;
  name: string;
  link: string;
  description: string;
  image: string;
  is_active: boolean;
}

export const brands: Brand[] = [
  {
    id: 1,
    name: 'VinFast',
    link: 'vinfast',
    description: 'VinFast - Vietnamese electric vehicle manufacturer',
    image: 'https://media.otozin.vn/vinfast.png',
    is_active: true,
  },
  {
    id: 2,
    name: 'Toyota',
    link: 'toyota',
    description: 'Toyota Motor Corporation - Japanese automotive manufacturer',
    image: 'https://media.otozin.vn/Toyota.png',
    is_active: true,
  },
  {
    id: 3,
    name: 'Honda',
    link: 'honda',
    description: 'Honda Motor Co., Ltd. - Japanese multinational corporation',
    image: 'https://media.otozin.vn/honda.png',
    is_active: true,
  },
  {
    id: 4,
    name: 'Ford',
    link: 'ford',
    description: 'Ford Motor Company - American multinational automobile manufacturer',
    image: 'https://media.otozin.vn/ford.png',
    is_active: true,
  },
  {
    id: 5,
    name: 'Hyundai',
    link: 'hyundai',
    description: 'Hyundai Motor Company - South Korean automotive manufacturer',
    image: 'https://media.otozin.vn/hyundai.png',
    is_active: true,
  },
  {
    id: 6,
    name: 'Kia',
    link: 'kia',
    description: 'Kia Corporation - South Korean automotive manufacturer',
    image: 'https://media.otozin.vn/kia.png',
    is_active: true,
  },
  {
    id: 7,
    name: 'Mazda',
    link: 'mazda',
    description: 'Mazda Motor Corporation - Japanese automotive manufacturer',
    image: 'https://media.otozin.vn/mazda.png',
    is_active: true,
  },
  {
    id: 8,
    name: 'Mitsubishi',
    link: 'mitsubishi',
    description: 'Mitsubishi Motors Corporation - Japanese automotive manufacturer',
    image: 'https://media.otozin.vn/mitsubishi.png',
    is_active: true,
  },
  {
    id: 9,
    name: 'Volkswagen',
    link: 'volkswagen',
    description: 'Volkswagen AG - German automotive manufacturer',
    image: 'https://media.otozin.vn/Volkswagen.png',
    is_active: true,
  },
  {
    id: 10,
    name: 'Nissan',
    link: 'nissan',
    description: 'Nissan Motor Co., Ltd. - Japanese automotive manufacturer',
    image: 'https://media.otozin.vn/nissan.png',
    is_active: true,
  },
  {
    id: 11,
    name: 'Suzuki',
    link: 'suzuki',
    description: 'Suzuki Motor Corporation - Japanese automotive manufacturer',
    image: 'https://media.otozin.vn/Suzuki.png',
    is_active: true,
  },
  {
    id: 12,
    name: 'Peugeot',
    link: 'peugeot',
    description: 'Peugeot - French automotive manufacturer',
    image: 'https://media.otozin.vn/peugeot.png',
    is_active: true,
  },
  {
    id: 13,
    name: 'Isuzu',
    link: 'isuzu',
    description: 'Isuzu Motors Limited - Japanese commercial vehicle manufacturer',
    image: 'https://media.otozin.vn/Isuzu.png',
    is_active: true,
  },
  {
    id: 14,
    name: 'Chevrolet',
    link: 'chevrolet',
    description: 'Chevrolet - American automotive brand',
    image: 'https://media.otozin.vn/chevrolet.png',
    is_active: true,
  },
  {
    id: 15,
    name: 'BMW',
    link: 'bmw',
    description: 'Bayerische Motoren Werke AG - German luxury vehicle manufacturer',
    image: 'https://media.otozin.vn/bmw.png',
    is_active: true,
  },
  {
    id: 16,
    name: 'Mercedes',
    link: 'mercedes',
    description: 'Mercedes-Benz Group AG - German luxury automotive brand',
    image: 'https://media.otozin.vn/mercedes.png',
    is_active: true,
  },
  {
    id: 17,
    name: 'Audi',
    link: 'audi',
    description: 'Audi AG - German luxury automotive manufacturer',
    image: 'https://media.otozin.vn/audi.png',
    is_active: true,
  },
  {
    id: 18,
    name: 'Lexus',
    link: 'lexus',
    description: 'Lexus - Japanese luxury vehicle division of Toyota',
    image: 'https://media.otozin.vn/Lexus.png',
    is_active: true,
  },
  {
    id: 19,
    name: 'Land Rover',
    link: 'landrover',
    description: 'Land Rover - British luxury SUV manufacturer',
    image: 'https://media.otozin.vn/landrover.png',
    is_active: true,
  },
  {
    id: 20,
    name: 'Porsche',
    link: 'porsche',
    description: 'Porsche AG - German luxury sports car manufacturer',
    image: 'https://media.otozin.vn/porsche.png',
    is_active: true,
  },
];

